# Generated by Django 5.0.6 on 2025-02-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='course',
            field=models.CharField(choices=[('django', 'Django'), ('js', 'JavaScripts'), ('python', 'Python'), ('ML', 'Machine Learning')], max_length=50),
        ),
    ]
